Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
readme_file_bytes = Path("README.md").read_bytes()

message_crc = zlib.adler32(readme_file_bytes)

print(f"Checksum (Adler32): {message_crc}")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_1772/3499109848.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mreadme_file_bytes[0m [0;34m=[0m [0mPath[0m[0;34m([0m[0;34m"README.md"[0m[0;34m)[0m[0;34m.[0m[0mread_bytes[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mmessage_crc[0m [0;34m=[0m [0mzlib[0m[0;34m.[0m[0madler32[0m[0;34m([0m[0mreadme_file_bytes[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mprint[0m[0;34m([0m[0;34mf"Checksum (Adler32): {message_crc}"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pathlib.py[0m in [0;36mread_bytes[0;34m(self)[0m
[1;32m   1227[0m         [0mOpen[0m [0mthe[0m [0mfile[0m [0;32min[0m [0mbytes[0m [0mmode[0m[0;34m,[0m [0mread[0m [0mit[0m[0;34m,[0m [0;32mand[0m [0mclose[0m [0mthe[0m [0mfile[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1228[0m         """
[0;32m-> 1229[0;31m         [0;32mwith[0m [0mself[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mmode[0m[0;34m=[0m[0;34m'rb'[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1230[0m             [0;32mreturn[0m [0mf[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1231[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pathlib.py[0m in [0;36mopen[0;34m(self, mode, buffering, encoding, errors, newline)[0m
[1;32m   1220[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0m_closed[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1221[0m             [0mself[0m[0;34m.[0m[0m_raise_closed[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1222[0;31m         return io.open(self, mode, buffering, encoding, errors, newline,
[0m[1;32m   1223[0m                        opener=self._opener)
[1;32m   1224[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pathlib.py[0m in [0;36m_opener[0;34m(self, name, flags, mode)[0m
[1;32m   1076[0m     [0;32mdef[0m [0m_opener[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mflags[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0;36m0o666[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1077[0m         [0;31m# A stub for the opener argument to built-in open()[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1078[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_accessor[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mflags[0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1079[0m [0;34m[0m[0m
[1;32m   1080[0m     [0;32mdef[0m [0m_raw_open[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mflags[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0;36m0o777[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'README.md'
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

